follower_control:
  # Method
  mode : uwb # uwb / aruco / auto

  # Robot Movement
  constant_speed : false # Constant Forward Speed
  max_fwd : 0.5 # Max forward/reverse speed
  max_rot : 0.5 # Max rotation speed
  kp_fwd : 0.1  # Forward Error Bias
  kp_rot : 0.3  # Rotation Error Bias

  # Robot Target Tolerance
  err_fwd : 0.1 # front/back target error
  err_rot : 0.1 # side to side target error