camera_id: 4              # camera id
max_speed: 1.0            # m/s
max_turn: 0.8             # rad/s
tgt_stop_dist: 0.5        # m, stop distance threshold for target to follow, default is 0.5 m
obs_stop_dist: 0.3        # m, stop distance threshold for nearby obstacles, default is 0.3m
node_frequency: 40        # Hz, (jetson max realsense fps is 40-ish fps) --> for color detection set to 30
use_aruco: true   
camera_fps: 60